services:
  nextjs:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    working_dir: /app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - FAST_REFRESH=true
    volumes:
      - ./8inf886_projet_1:/app
      - /app/node_modules
      - /app/.next
