# Development image
FROM node:22

WORKDIR /app

# Install dependencies
COPY ./8inf886_projet_1/package*.json ./

RUN npm i

# Copy source
ADD ./8inf886_projet_1 .

# Expose dev server port
EXPOSE 3000

# Start Next.js in development mode
CMD ["npm", "run", "dev"]
